<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  ASSIGNMENT 
[
         
<!ELEMENT ASSIGNMENT (ROOM | MANUFACTURER | FURNISHING)*>
<!ELEMENT ROOM (LENGTH,WIDTH)>
<!ATTLIST ROOM RNAME ID #REQUIRED>
<!ELEMENT LENGTH (#PCDATA)>
<!ELEMENT WIDTH (#PCDATA)>
<!ELEMENT MANUFACTURER (NAME,CONTACT)>
<!ATTLIST MANUFACTURER MID ID #REQUIRED>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT CONTACT (#PCDATA)>
<!ELEMENT FURNISHING (TYPE)>
<!ATTLIST FURNISHING FID ID #REQUIRED>
<!ATTLIST FURNISHING NAMEFK IDREF #REQUIRED>
<!ATTLIST FURNISHING MIDFK IDREF #REQUIRED>
<!ELEMENT TYPE (#PCDATA)>
 ]>
<ASSIGNMENT>
	<ROOM RNAME="Room1">
		<LENGTH>5</LENGTH>
		<WIDTH>7</WIDTH>
	</ROOM>
	<ROOM RNAME="Room2">
		<LENGTH>12</LENGTH>
		<WIDTH>5</WIDTH>
	</ROOM>
	<ROOM RNAME="Room3">
		<LENGTH>8</LENGTH>
		<WIDTH>19</WIDTH>
	</ROOM>
	<ROOM RNAME="Room4">
		<LENGTH>16</LENGTH>
		<WIDTH>9</WIDTH>
	</ROOM>
	<ROOM RNAME="Room5">
		<LENGTH>18</LENGTH>
		<WIDTH>7</WIDTH>
	</ROOM>
	<ROOM RNAME="Room6">
		<LENGTH>3</LENGTH>
		<WIDTH>9</WIDTH>
	</ROOM>

	<MANUFACTURER MID ="Manufacturer1">
		<NAME>Retails</NAME>
		<CONTACT>9867258921</CONTACT>
	</MANUFACTURER>
	<MANUFACTURER MID ="Manufacturer2">
		<NAME>Ragam</NAME>
		<CONTACT>9980889221</CONTACT>
	</MANUFACTURER>
	<MANUFACTURER MID ="Manufacturer3">
		<NAME>MK Raj</NAME>
		<CONTACT>6592056143</CONTACT>
	</MANUFACTURER>
	<MANUFACTURER MID ="Manufacturer4">
		<NAME>Iola Smith</NAME>
		<CONTACT>9987168921</CONTACT>
	</MANUFACTURER>
	<MANUFACTURER MID ="Manufacturer5">
		<NAME>Jaycob Rolyd</NAME>
		<CONTACT>9998165342</CONTACT>
	</MANUFACTURER>

	<FURNISHING FID ="Furni1" NAMEFK ="Room2" MIDFK ="Manufacturer1" >
		<TYPE>Chairs</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni2" NAMEFK ="Room3" MIDFK ="Manufacturer2" >
		<TYPE>Tables</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni3" NAMEFK ="Room1" MIDFK ="Manufacturer4" >
		<TYPE>Sofas</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni4" NAMEFK ="Room4" MIDFK ="Manufacturer3" >
		<TYPE>Dining Tables</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni5" NAMEFK ="Room1" MIDFK ="Manufacturer2" >
		<TYPE>Beds</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni6" NAMEFK ="Room5" MIDFK ="Manufacturer2" >
		<TYPE>Desk</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni7" NAMEFK ="Room1" MIDFK ="Manufacturer5" >
		<TYPE>Dresser</TYPE>
	</FURNISHING>
	<FURNISHING FID ="Furni8" NAMEFK ="Room2" MIDFK ="Manufacturer1" >
		<TYPE>Ottomans</TYPE>
	</FURNISHING>
</ASSIGNMENT>	